# Generated by Django 4.1.5 on 2023-01-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iplist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=120)),
                ('ip_address', models.CharField(max_length=120)),
                ('site', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=80)),
                ('user_name', models.CharField(max_length=120)),
                ('mac_address', models.CharField(max_length=120)),
            ],
        ),
    ]
