# Generated by Django 4.1.5 on 2023-01-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='iplist',
            new_name='ip',
        ),
    ]
