# Generated by Django 4.1.5 on 2023-01-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0002_rename_iplist_ip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ip',
            new_name='iplist',
        ),
    ]
